version: '3.5'
services:
  backend:
    build:
      context: ./backend
    ports:
      - 8080:8080
    environment:
      - POSTGRES_HOST=postgres-container
      - REDIS_HOST=redis-container
      - REQUEST_ORIGIN=http://localhost
    container_name: backend-container
  frontend:
    build:
      context: ./frontend
    ports:
      - 5000:5000
    container_name: frontend-container
  redis:
    image: redis
    command: redis-server --appendonly yes
    restart: unless-stopped
    ports:
      - 6379:6379
    volumes:
      - ./database_redis:/data
    container_name: redis-container
  db:
    image: postgres
    restart: unless-stopped
    ports:
      - 5432:5432
    volumes:
      - ./database:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASE=postgres
    container_name: postgres-container
  load-balancer:
    image: jwilder/nginx-proxy
    volumes: 
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    container_name: load-balancer
  